=== api-evangelist/argo-cd/json-schema/argo-cd-v1alpha1-scm-provider-generator-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-cd/refs/heads/main/json-schema/argo-cd-v1alpha1-scm-provider-generator-schema.json",
  "title": "v1alpha1SCMProviderGenerator",
  "description": "SCMProviderGenerator defines a generator that scrapes a SCMaaS API to find candidate repos.",
  "type": "object",
  "properties": {
    "awsCodeCommit": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorAWSCodeCommit"
    },
    "azureDevOps": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorAzureDevOps"
    },
    "bitbucket": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorBitbucket"
    },
    "bitbucketServer": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorBitbucketServer"
    },
    "cloneProtocol": {
      "description": "Which protocol to use for the SCM URL. Default is provider-specific but ssh if possible. Not all providers\nnecessarily support all protocols.",
      "type": "string"
    },
    "filters": {
      "description": "Filters for which repos should be considered.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/v1alpha1SCMProviderGeneratorFilter"
      }
    },
    "gitea": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorGitea"
    },
    "github": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorGithub"
    },
    "gitlab": {
      "$ref": "#/definitions/v1alpha1SCMProviderGeneratorGitlab"
    },
    "requeueAfterSeconds": {
      "description": "Standard parameters.",
      "type": "integer",
      "format": "int64"
    },
    "template": {
      "$ref": "#/definitions/v1alpha1ApplicationSetTemplate"
    },
    "values": {
      "type": "object",
      "title": "Values contains key/value pairs which are passed directly as parameters to the template",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== api-evangelist/argo-cd/examples/argo-cd-v1alpha1-scm-provider-generator-example.json
{
  "awsCodeCommit": "abc1234def5678",
  "azureDevOps": "example-azuredevops",
  "bitbucket": "example-bitbucket",
  "bitbucketServer": "https://kubernetes.default.svc",
  "cloneProtocol": "example-cloneprotocol",
  "filters": [
    "example-filters",
    "example-filters"
  ],
  "gitea": "example-gitea",
  "github": "example-github",
  "gitlab": "example-gitlab",
  "requeueAfterSeconds": 230,
  "template": "example-template",
  "values": {}
}
