=== api-evangelist/argo-cd/json-schema/argo-cd-version-version-message-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-cd/refs/heads/main/json-schema/argo-cd-version-version-message-schema.json",
  "title": "versionVersionMessage",
  "description": "versionVersionMessage schema from Argo CD API",
  "type": "object",
  "properties": {
    "BuildDate": {
      "type": "string"
    },
    "Compiler": {
      "type": "string"
    },
    "ExtraBuildInfo": {
      "type": "string"
    },
    "GitCommit": {
      "type": "string"
    },
    "GitTag": {
      "type": "string"
    },
    "GitTreeState": {
      "type": "string"
    },
    "GoVersion": {
      "type": "string"
    },
    "HelmVersion": {
      "type": "string"
    },
    "JsonnetVersion": {
      "type": "string"
    },
    "KubectlVersion": {
      "type": "string"
    },
    "KustomizeVersion": {
      "type": "string"
    },
    "Platform": {
      "type": "string"
    },
    "Version": {
      "type": "string"
    }
  }
}

=== api-evangelist/argo-cd/examples/argo-cd-version-version-message-example.json
{
  "BuildDate": "example-builddate",
  "Compiler": "example-compiler",
  "ExtraBuildInfo": "example-extrabuildinfo",
  "GitCommit": "abc1234def5678",
  "GitTag": "example-gittag",
  "GitTreeState": "example-gittreestate",
  "GoVersion": "v2.14.0",
  "HelmVersion": "v2.14.0",
  "JsonnetVersion": "v2.14.0",
  "KubectlVersion": "v2.14.0",
  "KustomizeVersion": "v2.14.0",
  "Platform": "example-platform",
  "Version": "v2.14.0"
}
