=== api-evangelist/argo-cd/json-schema/argo-cd-v1alpha1-repo-creds-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-cd/refs/heads/main/json-schema/argo-cd-v1alpha1-repo-creds-schema.json",
  "title": "v1alpha1RepoCreds",
  "description": "v1alpha1RepoCreds schema from Argo CD API",
  "type": "object",
  "properties": {
    "azureActiveDirectoryEndpoint": {
      "type": "string",
      "title": "AzureActiveDirectoryEndpoint specifies the Azure Active Directory endpoint used for Service Principal authentication. If empty will default to https://login.microsoftonline.com"
    },
    "azureServicePrincipalClientId": {
      "type": "string",
      "title": "AzureServicePrincipalClientId specifies the client ID of the Azure Service Principal used to access the repo"
    },
    "azureServicePrincipalClientSecret": {
      "type": "string",
      "title": "AzureServicePrincipalClientSecret specifies the client secret of the Azure Service Principal used to access the repo"
    },
    "azureServicePrincipalTenantId": {
      "type": "string",
      "title": "AzureServicePrincipalTenantId specifies the tenant ID of the Azure Service Principal used to access the repo"
    },
    "bearerToken": {
      "type": "string",
      "title": "BearerToken contains the bearer token used for Git BitBucket Data Center auth at the repo server"
    },
    "enableOCI": {
      "type": "boolean",
      "title": "EnableOCI specifies whether helm-oci support should be enabled for this repo"
    },
    "forceHttpBasicAuth": {
      "type": "boolean",
      "title": "ForceHttpBasicAuth specifies whether Argo CD should attempt to force basic auth for HTTP connections"
    },
    "gcpServiceAccountKey": {
      "type": "string",
      "title": "GCPServiceAccountKey specifies the service account key in JSON format to be used for getting credentials to Google Cloud Source repos"
    },
    "githubAppEnterpriseBaseUrl": {
      "type": "string",
      "title": "GithubAppEnterpriseBaseURL specifies the GitHub API URL for GitHub app authentication. If empty will default to https://api.github.com"
    },
    "githubAppID": {
      "type": "integer",
      "format": "int64",
      "title": "GithubAppId specifies the Github App ID of the app used to access the repo for GitHub app authentication"
    },
    "githubAppInstallationID": {
      "type": "integer",
      "format": "int64",
      "title": "GithubAppInstallationId specifies the ID of the installed GitHub App for GitHub app authentication"
    },
    "githubAppPrivateKey": {
      "type": "string",
      "title": "GithubAppPrivateKey specifies the private key PEM data for authentication via GitHub app"
    },
    "insecureOCIForceHttp": {
      "description": "InsecureOCIForceHttp specifies whether the connection to the repository uses TLS at _all_. If true, no TLS. This flag is applicable for OCI repos only.",
      "type": "boolean"
    },
    "noProxy": {
      "type": "string",
      "title": "NoProxy specifies a list of targets where the proxy isn't used, applies only in cases where the proxy is applied"
    },
    "password": {
      "type": "string",
      "title": "Password for authenticating at the repo server"
    },
    "proxy": {
      "type": "string",
      "title": "Proxy specifies the HTTP/HTTPS proxy used to access repos at the repo server"
    },
    "sshPrivateKey": {
      "type": "string",
      "title": "SSHPrivateKey contains the private key data for authenticating at the repo server using SSH (only Git repos)"
    },
    "tlsClientCertData": {
      "type": "string",
      "title": "TLSClientCertData specifies the TLS client cert data for authenticating at the repo server"
    },
    "tlsClientCertKey": {
      "type": "string",
      "title": "TLSClientCertKey specifies the TLS client cert key for authenticating at the repo server"
    },
    "type": {
      "description": "Type specifies the type of the repoCreds. Can be either \"git\", \"helm\" or \"oci\". \"git\" is assumed if empty or absent.",
      "type": "string"
    },
    "url": {
      "type": "string",
      "title": "URL is the URL to which these credentials match"
    },
    "useAzureWorkloadIdentity": {
      "type": "boolean",
      "title": "UseAzureWorkloadIdentity specifies whether to use Azure Workload Identity for authentication"
    },
    "username": {
      "type": "string",
      "title": "Username for authenticating at the repo server"
    }
  }
}

=== api-evangelist/argo-cd/examples/argo-cd-v1alpha1-repo-creds-example.json
{
  "azureActiveDirectoryEndpoint": "example-azureactivedirectory",
  "azureServicePrincipalClientId": "app-123456",
  "azureServicePrincipalClientSecret": "example-azureserviceprincipa",
  "azureServicePrincipalTenantId": "app-123456",
  "bearerToken": "eyJhbGciOiJIUzI1NiJ9.example",
  "enableOCI": true,
  "forceHttpBasicAuth": true,
  "gcpServiceAccountKey": "eyJhbGciOiJIUzI1NiJ9.example",
  "githubAppEnterpriseBaseUrl": "https://github.com/example/repo.git",
  "githubAppID": 443,
  "githubAppInstallationID": 817,
  "githubAppPrivateKey": "eyJhbGciOiJIUzI1NiJ9.example",
  "insecureOCIForceHttp": true,
  "noProxy": "example-noproxy",
  "password": "example-password",
  "proxy": "example-proxy",
  "sshPrivateKey": "eyJhbGciOiJIUzI1NiJ9.example",
  "tlsClientCertData": "example-tlsclientcertdata",
  "tlsClientCertKey": "eyJhbGciOiJIUzI1NiJ9.example",
  "type": "example-type",
  "url": "https://github.com/example/repo.git",
  "useAzureWorkloadIdentity": true,
  "username": "my-application"
}
