=== api-evangelist/argo-cd/json-schema/argo-cd-v1alpha1-application-spec-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-cd/refs/heads/main/json-schema/argo-cd-v1alpha1-application-spec-schema.json",
  "title": "v1alpha1ApplicationSpec",
  "description": "ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.",
  "type": "object",
  "properties": {
    "destination": {
      "$ref": "#/definitions/v1alpha1ApplicationDestination"
    },
    "ignoreDifferences": {
      "type": "array",
      "title": "IgnoreDifferences is a list of resources and their fields which should be ignored during comparison",
      "items": {
        "$ref": "#/definitions/v1alpha1ResourceIgnoreDifferences"
      }
    },
    "info": {
      "type": "array",
      "title": "Info contains a list of information (URLs, email addresses, and plain text) that relates to the application",
      "items": {
        "$ref": "#/definitions/v1alpha1Info"
      }
    },
    "project": {
      "description": "Project is a reference to the project this application belongs to.\nThe empty string means that application belongs to the 'default' project.",
      "type": "string"
    },
    "revisionHistoryLimit": {
      "description": "RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for informational purposes as well as for rollbacks to previous versions.\nThis should only be changed in exceptional circumstances.\nSetting to zero will store no history. This will reduce storage used.\nIncreasing will increase the space used to store the history, so we do not recommend increasing it.\nDefault is 10.",
      "type": "integer",
      "format": "int64"
    },
    "source": {
      "$ref": "#/definitions/v1alpha1ApplicationSource"
    },
    "sourceHydrator": {
      "$ref": "#/definitions/v1alpha1SourceHydrator"
    },
    "sources": {
      "type": "array",
      "title": "Sources is a reference to the location of the application's manifests or chart",
      "items": {
        "$ref": "#/definitions/v1alpha1ApplicationSource"
      }
    },
    "syncPolicy": {
      "$ref": "#/definitions/v1alpha1SyncPolicy"
    }
  }
}

=== api-evangelist/argo-cd/examples/argo-cd-v1alpha1-application-spec-example.json
{
  "destination": "example-destination",
  "ignoreDifferences": [
    "example-ignoredifferences",
    "example-ignoredifferences"
  ],
  "info": [
    "example-info",
    "example-info"
  ],
  "project": "default",
  "revisionHistoryLimit": 451,
  "source": "example-source",
  "sourceHydrator": "example-sourcehydrator",
  "sources": [
    "example-sources",
    "example-sources"
  ],
  "syncPolicy": "example-syncpolicy"
}
